INSERT INTO cities (cityName) VALUES
('Berlin'),
('Hamburg'),
('München'),
('Köln'),
('Frankfurt am Main'),
('Stuttgart'),
('Düsseldorf'),
('Dortmund'),
('Essen'),
('Bremen'),
('Leipzig'),
('Dresden'),
('Hannover'),
('Nürnberg'),
('Duisburg'),
('Bochum'),
('Wuppertal'),
('Bonn'),
('Bielefeld'),
('Mannheim'),
('Karlsruhe'),
('Münster'),
('Wiesbaden'),
('Augsburg'),
('Aachen'),
('Mönchengladbach'),
('Gelsenkirchen'),
('Braunschweig'),
('Chemnitz'),
('Kiel'),
('Krefeld'),
('Halle (Saale)'),
('Magdeburg'),
('Freiburg im Breisgau'),
('Oberhausen'),
('Lübeck'),
('Erfurt'),
('Rostock'),
('Mainz'),
('Kassel'),
('Hagen'),
('Hamm'),
('Saarbrücken'),
('Mülheim an der Ruhr'),
('Herne'),
('Ludwigshafen am Rhein'),
('Osnabrück'),
('Oldenburg'),
('Leverkusen'),
('Solingen'),
('Potsdam'),
('Neuss'),
('Heidelberg'),
('Paderborn'),
('Darmstadt'),
('Regensburg'),
('Würzburg'),
('Ingolstadt'),
('Heilbronn'),
('Ulm'),
('Göttingen'),
('Offenbach am Main'),
('Pforzheim'),
('Recklinghausen'),
('Bottrop'),
('Fürth'),
('Bremerhaven'),
('Reutlingen'),
('Remscheid'),
('Koblenz'),
('Bergisch Gladbach'),
('Erlangen'),
('Moers'),
('Trier'),
('Jena'),
('Siegen'),
('Hildesheim'),
('Wolfsburg'),
('Gera'),
('Zwickau');
