version: '3'

services: 
  php:
    build: .
    container_name: ticketShare_webserver
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: ticketShare_db
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql